# Generated by Django 3.2.9 on 2021-11-14 11:48

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211110_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='email',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name='Event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state_type',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], max_length=36, verbose_name=events.models.StateChoices['DRAFT']),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.CharField(max_length=300, verbose_name='Default comment'),
        ),
    ]
